### PR TITLE
64/missing images

### PR DESCRIPTION
**Pull request by azizmashkour**
@juancarlosfarah, this `pr` is to fix the previous issue you noticed about the images.
I am bit sick so was not able to work earlier. Thanks.

### CODE REVIEW

**Comment by azizmashkour** [comment]
This file is blocking all the commits, it requires to run `yarn upgrade caniuse-lite browserslist` but even while doing it continues failing that, why I deleted it. But I will search for a solution. Thanks

**Comment by juancarlosfarah** [comment]
@azizmashkour, the `caniuse` are just warnings, you can ignore that. Husky runs the git hooks, so probably the linter is failing. Check if `yarn lint` shows any warning. Or perhaps the tests.

**Comment by juancarlosfarah** [comment]
@azizmashkour, could you please have a look at what I mentioned about Husky. Otherwise I will deal with it.

**Comment by azizmashkour** [comment]
Yes, I will fix it today. Sorry I forgot.

**Comment by azizmashkour** [comment]
Hi @juancarlosfarah, I have been trying to fix the issue without success, the `yarn build` keep failing telling that `Error in parsing SVG: Non-whitespace before first tag`, any idea or path I can try to fix it please?

**Comment by juancarlosfarah** [comment]
Have you tried removing the `<?xml version="1.0" encoding="UTF-8"?>` line from the SVGs?

**Comment by azizmashkour** [comment]
Yes @juancarlosfarah. It seems wired, I even tried installing ` "@svgr/webpack": "4.3.3",` but it didn't work.

**Comment by juancarlosfarah** [comment]
@azizmashkour, I fixed it. You did not need the SVG loader. See my commit 03dd49366e515e1531e40e890ba6ade9499f125f for more details. Will go ahead and merge.

**Pull request merged**
